# Automatically close issues that have a keyword mark (an HTML comment)
# in the last comment in the issue, by a group of predefined users, after a custom delay.
# https://github.com/tiangolo/issue-manager
#
# Default to 10 days delay and comment:
# <!-- issue-manager: answered -->


name: Issue Manager

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
    - uses: tiangolo/issue-manager@0.3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        config: '{"answered": {}}'
