name: Upgrader

on:
  workflow_dispatch:
  schedule:
    - cron: "26 21 10 1-9,11-12 *"

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/poetry-upgrade.yml@v1
    secrets:
      gh_pat: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
